remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
show_downloads: true
logo: /logo.png
title: ./bercon
description: BattlEye RCON CLI
markdown: GFM
github:
  zip_url: https://github.com/WoozyMasta/bercon/zipball/master
  tar_url: https://github.com/WoozyMasta/bercon/tarball/master
  linux: https://github.com/WoozyMasta/bercon/releases/latest/download/bercon
  windows: https://github.com/WoozyMasta/bercon/releases/latest/download/bercon.exe
